.TH SPOOKY 1
.SH NAME
spooky \- print (n)spooky(n+2)me
.SH SYNOPSIS
.B spooky
[\fB\-n\fR \fINUMBER\fR]
.SH DESCRIPTION
.B spooky
prints a line describing how spooky something is based on the 2spooky4me form.
.SH OPTIONS
.TP
.BR \-n=\fINUMBER\fR
Set the first number, must be a positive integer. Default is 2.
